modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/davidjjung/just_dandy/issues"
license = "MIT License"

[[mixins]]
config = "just_dandy.mixins.json"

[[mods]]
    modId = "just_dandy"
    version = "${mod_version}"
    logoFile = "logo.png"
    itemIcon = "just_dandy:fluffy_dandelion"
    configBackground = "minecraft:textures/block/yellow_wool.png"
    authors = "DavigJ"
    credits = "Booleven, bageldotjpg, gladosedition"
    displayURL = "https://modrinth.com/project/just-dandy"
    displayName = "Just Dandy"
    description = '''
    Adds a little visual fluff to some biomes.
    '''

[[dependencies.just_dandy]]
    modId = "minecraft"
    type = "required"
    versionRange = "[${mc_version}]"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.just_dandy]]
    modId = "neoforge"
    type = "required"
    versionRange = "[${neoforge},)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.just_dandy]]
    modId = "blueprint"
    type = "required"
    versionRange = "[${blueprint},)"
    ordering = "AFTER"
    side = "BOTH"